version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3002:3002
    platform: linux/x86_64
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./backend/src:/app-backend/src
    depends_on:
      - db
    environment:
      - APP_PORT=3002
      - JWT_SECRET=jwt_secret
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432
  db:
    image: postgres:14.2-alpine
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: NG_CASH
    restart: 'always'
